# Generated by Django 3.0 on 2021-09-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_family_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='members',
        ),
    ]
