# Generated by Django 3.0 on 2021-09-15 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_family_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(through='api.Parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
